apiVersion: v1
kind: Pod
metadata:
  name: attacker-pod
  namespace: attacker
  labels:
    app: attacker
spec:
  containers:
  - name: attacker
    image: nicolaka/netshoot
    command: ["/bin/bash"]
    args: ["-c", "while true; do sleep 30; done"]

